# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'DnaLocationSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DnaLocationSample
  pod 'DnaLocation', :path => '../DnaLocation'
end
